//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public tblCountry()
        {
            this.tblTouristplaces = new HashSet<tblTouristplace>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> Latitude { get; set; }
        public Nullable<long> Longitude { get; set; }
    
        public virtual ICollection<tblTouristplace> tblTouristplaces { get; set; }
    }
}
