//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTouristplace
    {
        public int TouristplaceId { get; set; }
        public string PlaceName { get; set; }
        public Nullable<long> Latitude { get; set; }
        public Nullable<long> Longitude { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PhotoPath { get; set; }
        public string Description { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
